### ISSUE TITLE
Feature request - Disable notifications

### ISSUE THREAD

**Issue by Unkorneglosk** [LucasitoInDev/crowty-anti-sign-edit#2]
Hi ! 
I know it might not be the right way to do it but I think it could be a good idea to let admins hide the "You don't have the permission" sign.
I actually never made anything using Java but I could also try.

**Comment by LucasitoInDev** [comment]
Great idea! Ill be available on next Monday minor update! 🤩

**Comment by LucasitoInDev** [comment]
Applied! [Commit f056ff3](https://github.com/LucasitoInDev/crowty-anti-sign-edit/commit/f17493451be190845227224a760424df9f17fa27)

I have added a key to the settings, setting it to 'false' will not send any message to the user when editing is denied.

`notify-nopermission: true #If set to 'false' nothing will be sent to the user`
